language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
# command to install dependencies
install:
  - pip uninstall -y six
  - pip install six>=1.11.0
  - pip install requests_mock
  - pip install -e .
# command to run tests
script: python setup.py test